// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-services.ts
var list_services_default = defineTool({
  name: "list_services",
  title: "List massage services",
  description: "List the bookable Massavo massage services with duration and price.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of services to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("services").select("id, name, description, duration_minutes, price, is_active").eq("is_active", true).order("price").limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-cities.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_cities_default = defineTool2({
  name: "list_cities",
  title: "List cities",
  description: "List active cities where Massavo operates, with their gym counts.",
  inputSchema: {
    search: z2.string().trim().min(1).optional().describe("Optional case-insensitive city name filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cities").select("id, name, country, gym_count").eq("is_active", true).order("name");
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query.limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-venues.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_venues_default = defineTool3({
  name: "list_venues",
  title: "List gyms and hotels",
  description: "List active Massavo partner gyms (and optionally hotels), filtered by city.",
  inputSchema: {
    city_id: z3.string().uuid().optional().describe("Only return venues in this city."),
    venue_type: z3.enum(["gym", "hotel"]).optional().describe("Venue type; defaults to gym.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city_id, venue_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const table = venue_type === "hotel" ? "hotels" : "gyms";
    let query = supabase.from(table).select("id, name, address, city_id, open_hours, rating, review_count").eq("is_active", true).order("name");
    if (city_id) query = query.eq("city_id", city_id);
    const { data, error } = await query.limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { venues: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_my_bookings_default = defineTool4({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List the signed-in user's own Massavo bookings, newest first.",
  inputSchema: {
    status: z4.enum(["pending", "confirmed", "completed", "cancelled", "rescheduled"]).optional().describe("Optional booking status filter."),
    limit: z4.number().int().min(1).max(50).optional().describe("Maximum number of bookings to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select(
      "id, booking_date, booking_time, status, payment_status, total_amount, currency, service_name_snapshot, gym_id, hotel_id, notes"
    ).eq("user_id", ctx.getUserId()).order("booking_date", { ascending: false }).order("booking_time", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query.limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-booking.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var get_booking_default = defineTool5({
  name: "get_booking",
  title: "Get booking details",
  description: "Get details of one of the signed-in user's bookings by its id.",
  inputSchema: {
    booking_id: z5.string().uuid().describe("The booking id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ booking_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("bookings").select(
      "id, booking_date, booking_time, status, payment_status, total_amount, currency, service_name_snapshot, service_price_snapshot, gym_id, hotel_id, notes, created_at"
    ).eq("id", booking_id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Booking not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lugzhjfguftlfcgjfnbj";
var mcp_default = defineMcp({
  name: "massavo-com",
  title: "Massavo.com",
  version: "0.1.0",
  instructions: "Tools for Massavo, a mobile massage and recovery platform operating inside partner gyms and hotels. Use `list_cities` and `list_venues` to explore locations, `list_services` for bookable treatments, and `list_my_bookings` / `get_booking` to read the signed-in user's own appointments.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_cities_default, list_venues_default, list_services_default, list_my_bookings_default, get_booking_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
